### ISSUE TITLE
"ustar " instead of "ustar"

### ISSUE THREAD

**Issue by nazar-pc** [clue/reactphp-tar#7]
This tarball: https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
If has magic header recognized as `ustar ` instead of `ustar` (note space at the end).
After manual code tweaking it extracts files just fine.

**Comment by clue** [comment]
@nazar-pc Thanks for reporting!

The linked tar file uses the `ustar  ` (7 bytes with two trailing spaces) format which is also known as "oldgnu" or "GNU tar" format. Short link dump:

* http://www.gnu.org/software/tar/manual/html_node/Standard.html
* `struct header_gnu_tar` https://github.com/libarchive/libarchive/wiki/ManPageTar5#gnu-tar-archives

As such, this is not the same as the current "ustar" format (POSIX IEEE P1003.1). There already an open ticket to add support for more formats in the future via #3, so I'll close this one as a possible duplicate.

If you want to sponsor this feature and/or help with implementation, feel free to reach out :+1:
